### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by wangpeng1** [yzcheng90/zhjg-common-autofull#3]
2023-10-16 13:53:15.093 ERROR 20000 --- [nio-8080-exec-3] com.zaxxer.hikari.pool.HikariPool        :HikariPool-1 - Exception during pool initialization.
java.sql.SQLSyntaxErrorException: Unknown database 'autofull'at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~~[mysql-connector-java-8.0.15.jar:8.0.15]

**Comment by yzcheng90** [comment]
有没有可能是你没有创建库导入sql?
https://github.com/yzcheng90/autofull/tree/master/example-sql

**Comment by wangpeng1** [comment]
@yzcheng90   导入了 只是没有命名数据库为 autofull。重新命名 autofull可以了 多谢。
